import NavMenu from './NavMenu';
import './globals.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextSpace',
  description: 'Generated by Next',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <NavMenu/>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
